<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "frp_example"
 *
 * Auto generated by Extension Builder 2015-09-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Example',
	'description' => 'Example extension.',
	'category' => 'distribution',
	'author' => '!frappant Webfactory',
	'author_email' => 'support@frappant.ch',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);